### ISSUE TITLE
Possibly flawed assumption in CMakeLists.txt?

### ISSUE THREAD

**Issue by copumpkin** [sambayless/monosat#11]
As mentioned in the last ticket, I'm packaging monosat and its language libraries for nixpkgs. In doing the java portion, I noticed that you have:

https://github.com/sambayless/monosat/blob/cbaf79cfd01cba97b46cae5a9d7b832771ff442c/CMakeLists.txt#L462

Which assumes that `CMAKE_BINARY_DIR` contains your source code. If you're doing an in-source build, that's generally true, but it's not required and in my case the two don't correspond, so `cmake` is unhappy and fails at that step.

**Comment by copumpkin** [comment]
Also, I think your reasoning for the `&& true` might suggest you want `|| true`?

**Comment by sambayless** [comment]
Thanks! Should be fixed in master now

**Comment by copumpkin** [comment]
Great, thanks! I'll update my package to avoid working around this stuff 😄
