### ISSUE TITLE
read_pb test fails because no-pb-binary-search flag is unknown

### ISSUE THREAD

**Issue by Hirse** [sambayless/monosat#5]
I just built the latest commit and ran the tests. The first one fails:
![image](https://user-images.githubusercontent.com/2564094/32253772-e9008242-be59-11e7-8fcc-1e46904a0c82.png)

https://github.com/sambayless/monosat/blob/6444d6be0c701bd312bfde4817584b5f7c64cf0d/tests/python/read_pb.py#L15

**Comment by sambayless** [comment]
Good catch! The option "-no-pb-binary-search" no longer exists. I will upload a fix for this test case shortly.
